### PR TITLE
feat: support GITHUB_TOKEN env variable by default

### PR DESCRIPTION
**Pull request by orgads**
It is commonly used.

### CODE REVIEW

**Comment by BePo65** [comment]
This is a breaking change and I am not yet completely convinced  that we should go this way.

The current implementation has the following priorities (via the default values in the config file and `tokenFromConfigObject`:
1. anonymous access to github (default; no entry in config or `tokenEnvVar===''`)
2. github token in a (secret) file (`tokenFileEnvVar!==''`)
3. github token in an environment variable (`tokenEnvVar!==''`)

Variant 1 being the most secure version (as we don't need any secrets :-) and variant 3 is for sure the most heavily used variant, but is also the least secure variant, as every program in a process sees all environment variables (that maybe fine for many environments).

When using the variant 3. i agree that it is inconvenient to set the name of the environment variable in the config, when in many (if not even in most) cases this will be the default name 'GITHUB_TOKEN'.

The problem is that i use 2 elements to represent 3 states.
Without thinking too much about possible solutions I could imagine at least 2 ways to solve this problem.
 1. add a 3rd entry to `githubToken`; something like `anonymous:true`
 2. change the properties of `githubToken` to something like
```
githubToken: {
    type: ' anonymous', // values. "anonymous", "file" or  "env"
    tokenEnvVar: 'GITHUB_TOKEN'
  }
```

Both solutions are breaking changes.
In solution 1, we can set tokenFileEnvVar as default to GITHUB_TOKEN and could change `tokenFromConfigObject` in a way that if `githubToken.anonymous!==true` `tokenFileEnvVar` is checked before `tokenEnvVar`.
This way we do not have to set  tokenFileEnvVar to GITHUB_TOKEN, but a property named `anonymous` or something like this looks pretty clumsy to me. perhaps you have a better name for it.

Solution 2 avoids this clumsiness.

What do you think about my ideas?

**Comment by orgads** [comment]
I'm not sure why you consider this a breaking change. If `GITHUB_TOKEN` is not set then everything works as it does currently.

Do you see a scenario where `GITHUB_TOKEN` *is* set, but not intended to be used?

**Comment by BePo65** [comment]
Ah, ok, i see. I missed the case that `tokenEnvVar===GITHUB_TOKEN`, but `GITHUB_TOKEN` is not set. In that case everything will run as if tokenEnvVar was not set.

So i will merge this pr. but before this, would you please be so kind to update readme file (line 66) and add a remark that the default name for the config parameter `tokenEnvVar` is GITHUB_TOKEN?

**Comment by orgads** [comment]
Sure, done.

**Comment by BePo65** [comment]
published it as v1.2.0

**Pull request merged**
